### ISSUE TITLE
Configure transparency percentage?

### ISSUE THREAD

**Issue by lourenzo** [thenewvu/atom-all-times-you-know#1]
Hello,
I really liked this extension, and I think it would be even greater if we could configure the transparency percentage.
If you're too busy now to implement this, I can make a PR.

Regards

**Comment by thenewvu** [comment]
Sorry for responding late. Currently I have no time for this package, please make a PR, all PR are welcome and appreciated. Thank you.

**Comment by thenewvu** [comment]
Hello @lourenzo,

If you actually want to change the background opacity, there is a way that you can do it by yourself.

Add this to your stylesheet:

``` less
.all-times-you-know {
  opacity: 0.5 !important; // what you want between 0.0 and 1.0
}
```
